version: '3'

services:
  mysql:
    image: mysql:5.7
    command: 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/:/var/lib/mysql/
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yearning
      MYSQL_DATABASE: yearning
      MYSQL_USER: yearning
      MYSQL_PASSWORD: yearning
    networks:
      - yearning
  yearning:
    image: hyr326/yearning:latest
    restart: on-failure
    depends_on: 
      - mysql
    ports:
      - "8000:8000"
    environment:
      MYSQL_ADDR: mysql:3306
      MYSQL_DB: yearning      
      MYSQL_USER: yearning
      MYSQL_PASSWORD: yearning
    networks:
      - yearning

networks:
  yearning:
