name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version
      run: echo $(grep "VERSION" Dockerfile | cut -d '' -f 2) >> $GITHUB_ENV
    - name: Build and publish images
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hyr326/yearning
        tags: "v${{ env.VERSION }},latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
