name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish images
      - pre: echo ::set-state name=VERSION::$(grep "VERSION=" Dockerfile |cut -d "=" -f2) 
      - uses: elgohr/Publish-Docker-Github-Action@master
      - with:
          name: hyr326/yearning
          tags: "v${{ env.STATE_VERSION }},latest"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
